import type { Metadata } from "next";
import "./globals.css";
import { ADLaM_Display, Poppins } from "next/font/google";

const adlam = ADLaM_Display({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-adlam",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${adlam.variable}`}>
      <body className="font-main overflow-x-hidden">{children}</body>
    </html>
  );
}
